/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6QsKxQAPgdi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardContent } from "@/components/ui/card"

 

export function Homepage() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };
  return (
    (<div style={{ color: 'white' }} className="min-h-screen bg-[#1b1b2f] text-white flex">
//btn
       <button
        onClick={toggleMenu}
        className="p-4 md:hidden flex items-center"
      >
        <MenuIcon className="h-6 w-6 text-white" />
      </button>
//btn


      <aside className={`fixed inset-0 top-16 md:relative md:w-60 md:flex md:flex-col space-y-6 transition-transform ${
          isMenuOpen ? "translate-x-0" : "-translate-x-full"
        } md:translate-x-0 bg-[#0f0f1d] p-4 md:p-4`}>
        <div className="flex items-center space-x-2">
          <TvIcon className="h-8 w-8 text-white" />
          <span className="text-2xl font-bold">SmartTV</span>
        </div>
        <nav className="flex flex-col text-white space-y-4">
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <HomeIcon className="h-5 w-5 text-white" />
            <span>Home</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <FilmIcon className="h-5 w-5 text-white" />
            <span>Movies</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <TvIcon className="h-5 w-5 text-white" />
            <span>TV Shows</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <LayersIcon className="h-5 w-5 text-white" />
            <span>Series</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <HeartIcon className="h-5 w-5 text-white" />
            <span>My Favorites</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <BookmarkIcon className="h-5 w-5 text-white" />
            <span>Wishlist</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <SettingsIcon className="h-5 w-5 text-white" />
            <span>Settings</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <LogOutIcon className="h-5 w-5 text-white" />
            <span>Logout</span>
          </Link>
        </nav>
      </aside>
      <main className="flex-1 p-6 space-y-8">
        <header className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Input
              type="search"
              placeholder="What are you looking for?"
              className="w-96 bg-[#2a2a3d] border-none text-white" />
            <SearchIcon className="h-5 w-5 text-white" />
          </div>
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" alt="User" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </header>
        <section className="relative">
          <img
            src="/placeholder.svg"
            alt="Lost In Space 2"
            className="w-full h-[400px] object-cover rounded-md"
            width="800"
            height="400"
            style={{ aspectRatio: "800/400", objectFit: "cover" }} />
          <div
            className="absolute inset-0 bg-gradient-to-t from-black to-transparent p-6 flex flex-col justify-end space-y-4">
            <h1 className="text-4xl font-bold">Lost In Space 2</h1>
            <p className="text-lg">A Netflix Original Series</p>
            <div className="flex items-center space-x-2">
              <span className="text-green-400">98% Match 2019</span>
              <Badge variant="secondary">18+</Badge>
            </div>
            <div className="flex space-x-4">
              <Button className="bg-blue-600">Watch Now</Button>
              <Button variant="outline">My List</Button>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Episodes</h2>
          <div className="grid grid-cols-4 gap-4">
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Shipwrecked"
                  className="w-full h-[150px] object-cover rounded-t-md"
                  width="250"
                  height="150"
                  style={{ aspectRatio: "250/150", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Shipwrecked</h3>
                <p className="text-sm text-muted-foreground">Episode 1</p>
                <span className="text-sm text-muted-foreground">50m</span>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Precipice"
                  className="w-full h-[150px] object-cover rounded-t-md"
                  width="250"
                  height="150"
                  style={{ aspectRatio: "250/150", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Precipice</h3>
                <p className="text-sm text-muted-foreground">Episode 2</p>
                <span className="text-sm text-muted-foreground">40m</span>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Echoes"
                  className="w-full h-[150px] object-cover rounded-t-md"
                  width="250"
                  height="150"
                  style={{ aspectRatio: "250/150", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Echoes</h3>
                <p className="text-sm text-muted-foreground">Episode 3</p>
                <span className="text-sm text-muted-foreground">44m</span>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Run"
                  className="w-full h-[150px] object-cover rounded-t-md"
                  width="250"
                  height="150"
                  style={{ aspectRatio: "250/150", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Run</h3>
                <p className="text-sm text-muted-foreground">Episode 5</p>
                <span className="text-sm text-muted-foreground">46m</span>
              </CardContent>
            </Card>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Recommended for you</h2>
          <div className="grid grid-cols-6 gap-4">
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Money Heist"
                  className="w-full h-[200px] object-cover rounded-t-md"
                  width="150"
                  height="200"
                  style={{ aspectRatio: "150/200", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Money Heist</h3>
                <p className="text-sm text-muted-foreground">Season 5</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Dark"
                  className="w-full h-[200px] object-cover rounded-t-md"
                  width="150"
                  height="200"
                  style={{ aspectRatio: "150/200", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Dark</h3>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Sacred Games"
                  className="w-full h-[200px] object-cover rounded-t-md"
                  width="150"
                  height="200"
                  style={{ aspectRatio: "150/200", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Sacred Games</h3>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Sabrina"
                  className="w-full h-[200px] object-cover rounded-t-md"
                  width="150"
                  height="200"
                  style={{ aspectRatio: "150/200", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Sabrina</h3>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="Sex Education"
                  className="w-full h-[200px] object-cover rounded-t-md"
                  width="150"
                  height="200"
                  style={{ aspectRatio: "150/200", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">Sex Education</h3>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-0">
                <img
                  src="/placeholder.svg"
                  alt="The Queen's Gambit"
                  className="w-full h-[200px] object-cover rounded-t-md"
                  width="150"
                  height="200"
                  style={{ aspectRatio: "150/200", objectFit: "cover" }} />
              </CardHeader>
              <CardContent className="p-4">
                <h3 className="text-lg font-bold">The Queen's Gambit</h3>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
    </div>)
  );
}

function BookmarkIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>)
  );
}


function FilmIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M7 3v18" />
      <path d="M3 7.5h4" />
      <path d="M3 12h18" />
      <path d="M3 16.5h4" />
      <path d="M17 3v18" />
      <path d="M17 7.5h4" />
      <path d="M17 16.5h4" />
    </svg>)
  );
}


function HeartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function LayersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
      <path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
      <path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
    </svg>)
  );
}


function LogOutIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}


function TvIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="15" x="2" y="7" rx="2" ry="2" />
      <polyline points="17 2 12 7 7 2" />
    </svg>)
  );
}
